# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: PowerShell@2
  displayName: "Inline powershell"
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Write-Host "Hello World from inline"

- task: PowerShell@2
  displayName: "powershell script"
  inputs:
    filePath: 'powershell.ps1'